name: PHP CodeSniffer によるコードチェック

on:
  pull_request:
    branches:
      - development

jobs:
  phpcs:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'

      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar global require "squizlabs/php_codesniffer=*"

      - name: Run PHP CodeSniffer and show output
        id: phpcs
        run: |
          phpcs --standard=PSR12 src/ --ignore=vendor/ --extensions=php
          exit_code=$?
          if [ $exit_code -ne 0 ]; then
            echo "::error file=src/,line=1::PHP CodeSniffer エラーがあります"  # エラーをアノテーションとして表示
            exit 1  # エラーがあればワークフローを失敗させる
          fi

      - name: Fail the workflow
        if: ${{ failure() }}
        run: |
          echo "PHP CodeSniffer チェックでエラーが検出されました。ワークフローを失敗させます。"
          exit 1