name: PHP CodeSniffer によるコードチェック実行

on:
  pull_request:
    branches:
      - development

jobs:
  phpcs:
    runs-on: ubuntu-latest

    env:
      TARGET_DIR: /home/runner/work/php_cs4/php_cs4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'

      - name: Copy files to target directory
        run: cp -r .github/* ${{ env.TARGET_DIR }}

      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar global require "squizlabs/php_codesniffer=*"

      - name: Run PHP CodeSniffer
        id: phpcs
        run: |
          phpcs --standard=${{ env.TARGET_DIR }}/phpcs.xml src/ --ignore=vendor/ --extensions=php
        continue-on-error: true