name: PHP CodeSniffer によるコードチェック

on:
  pull_request:
    branches:
      - development

jobs:
  phpcs:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'

      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php
          php composer.phar global require "squizlabs/php_codesniffer=*"

      - name: Run PHP CodeSniffer
        id: phpcs
        run: |
          result=$(phpcs --standard=PSR12 src/ --ignore=vendor/ --extensions=php)
          exit_code=$?
          echo "Result of PHP CodeSniffer:"
          echo "$result"
          echo "::set-output name=result::$result"
          if [ $exit_code -ne 0 ]; then
            exit $exit_code
          fi

      - name: Comment PHP CodeSniffer results on PR
        if: ${{ failure() }}
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### PHP CodeSnifferのエラーが検出されました:
            <details><summary>詳細を表示</summary>

            ```
            ${{ steps.phpcs.outputs.result }}
            ```
            </details>

      - name: Fail the workflow
        if: ${{ failure() }}
        run: |
          echo "PHP CodeSniffer チェックでエラーが検出されました。ワークフローを失敗させます。"
          exit 1